# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='importation_log',
            field=models.TextField(null=True, verbose_name=b'importation log'),
        ),
    ]
